#ifndef DEFINES_H
#define DEFINES_H

#define TEMPO_GERACAO 500

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 900

#define TAM_POPULACAO 2000
#define TAM_INDIVIDUOS 10.0f

#define VELOCIDADE_BASE 0.5f
#define VELOCIDADE_ANGULAR 0.01f
#define AMPLITUDE_ZIGUEZAGUE 3.0f
#define FREQUENCIA_ZIGUEZAGUE 3.0f

#define RAIO_MENOR 0.55f
#define RAIO_MAIOR 0.7f
#define RAIO_TORRE 0.12f

#define PROBABILIDADE_GENOCIDIO 0.01f
#define PROB_MORTE 0.2f
#define TAXA_MUTACAO 0.01f
#define TAXA_REMOCAO 0.2f

using namespace std;

#endif